version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    restart: unless-stopped
    user: root
    ports:
      - ${JENKINS_WEBAPP}:8080
      - ${JENKINS_OTHER}:50000
    container_name: jenkins
    networks:
      - gogs
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  
  postgres:
    image: postgres:9.5
    restart: unless-stopped
    environment:
     - "POSTGRES_USER=${POSTGRES_USER}"
     - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
     - "POSTGRES_DB=gogs"
    volumes:
     - "db-data:/var/lib/postgresql/data"
    networks:
     - gogs
  gogs:
    image: gogs/gogs:latest
    restart: unless-stopped
    ports:
     - "${gogs_SSL_port}:22"
     - "${gogs_web_port}:3000"
    links:
     - postgres
    environment:
     - "RUN_CROND=true"
    networks:
     - gogs
    volumes:
     - "gogs-data:/data"
    depends_on:
     - postgres
  registry:
   image: registry:2
   networks:
    - gogs
   ports:
   - ${DOCKER_REGISTRY_PORT}:5000
networks:
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "${PWD}/gogs-data"


