version: '3.8'
services:
  go-server:
    image: gocd/gocd-server:v17.9.0
    ports:
      - 8153:8153
      - 8154:8154
    volumes:
      - ./godata/config/cruise-config.xml:/godata/config/cruise-config.xml
    
    networks:
      - gogs
  go-agent1:
    image: gocd/gocd-agent-ubuntu-16.04:v17.9.0
    links:
      - "go-server"
    
    networks:
      - gogs
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: https://go-server:8154/go
  go-agent2:
    image: gocd/gocd-agent-ubuntu-16.04:v17.9.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    
    networks:
      - gogs
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: https://go-server:8154/go
  postgres:
    image: postgres:9.5
    restart: always
    environment:
     - "POSTGRES_USER=${POSTGRES_USER}"
     - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
     - "POSTGRES_DB=gogs"
    volumes:
     - "db-data:/var/lib/postgresql/data"
    networks:
     - gogs
  gogs:
    image: gogs/gogs:latest
    restart: always
    ports:
     - "${gogs_SSL_port}:22"
     - "${gogs_web_port}:3000"
    links:
     - postgres
    environment:
     - "RUN_CROND=true"
    networks:
     - gogs
    volumes:
     - "gogs-data:/data"
    depends_on:
     - postgres
  registry:
   image: registry:2
   ports:
   - ${DOCKER_REGISTRY_PORT}:5000
networks:
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
